export const manufacturers = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Bugatti",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "GMC",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Koenigsegg",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MINI",
  "Mitsubishi",
  "Nissan",
  "Porsche",
  "Pagani",
  "Ram",
  "Rolls-Royce",
  "Subaru",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
];

export const yearsOfProduction = [
  { title: "Year", value: "" },
  { title: "2015", value: "2015" },
  { title: "2016", value: "2016" },
  { title: "2017", value: "2017" },
  { title: "2018", value: "2018" },
  { title: "2019", value: "2019" },
  { title: "2020", value: "2020" },
  { title: "2021", value: "2021" },
  { title: "2022", value: "2022" },
  { title: "2023", value: "2023" },
  { title: "2024", value: "2024" },
];

export const fuels = [
  { title: "Fuel", value: "" },
  { title: "Gas", value: "Gas" },
  { title: "Electricity", value: "Electricity" },
];

export const footerLinks = [
  {
    title: 'About',
    links: [
      { title: 'How it works', url: '/', target: '_self' },
      { title: 'Featuerd', url: '/', target: '_self' },
      { title: 'Partnership', url: '/', target: '_self' },
      { title: 'Relations', url: '/', target: '_self' },
    ],
  },
  {
    title: 'Company',
    links: [
      { title: 'Events', url: '/', target: '_self' },
      { title: 'Blog', url: '/', target: '_self' },
      { title: 'Podcast', url: '/', target: '_self' },
      { title: 'Invite a friend', url: '/', target: '_self' },
    ],
  },
  {
    title: 'Socials',
    links: [
      { title: 'Facebook', target:'_blank', url: 'https://www.facebook.com/profile.php?id=100007766405910&ref=xav_ig_profile_web' ,},
      { title: 'LinkedIn', target:'_blank', url: 'https://www.linkedin.com/in/mostafa-mahmoud-33a1542b0' ,},
      { title: 'GitHub', target:'_blank', url: 'https://github.com/Mostafa3ta' ,},
      // { title: 'Instagram', target:'_blank', url: 'https://www.instagram.com/mostafa3ta_106?igsh=bXVoMm9yazcwdmlo' ,},
      { title: 'Profile', target:'_blank', url: 'https://portfolio-ten-tau-56.vercel.app/' ,},
    ],
  },
]